version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_TAG: vpalacio/toolbox:latest
    docker:
      - image: docker:git

jobs:
  lint:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint Dockerfile
          command: script/lint

  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: script/build
      - run:
          name: Save Docker image
          command: docker save -o /tmp/image.tar vpalacio/toolbox
      - persist_to_workspace:
          root: /tmp
          paths:
            - image.tar

  test:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image
          command: docker load -i /tmp/image.tar
      - run:
          name: Test Docker image
          command: script/test

  publish:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load Docker image
          command: docker load -i /tmp/image.tar
      - run:
          name: Publish Docker image
          command: script/publish

workflows:
  version: 2
  build-push:
    jobs:
      - lint
      - build:
          requires: [lint]
      - test:
          requires: [build]
      - publish:
          requires: [test]
          filters:
            branches:
              only: master
