#!/bin/sh
set -o nounset 
set -o errexit 
set -o xtrace

if [ -z ${CIRCLECI} ]; then
  echo This only runs on circleci. >&2
  exit 1
fi

. test/vars.bash

if [ ${CIRCLE_BRANCH} = "master" ]; then
# TAG="$(date +%Y%m%dT%H%M)-git-${GIT_HASH:0:7}"
  TAG="$(date +%Y%m%dT%H%M)-git-${CIRCLE_SHA1:0:7}"
  tags="${TAG} latest"
else
  TAG="${CIRCLE_PROJECT_USERNAME}_pull_${CIRCLE_SHA1:0:7}"
  tags="${TAG}"
fi

echo "${pass}" | docker login --username "${user}" --password-stdin
for tag in ${tags}; do
  docker tag ${IMAGE} ${IMAGE}:${tag}
  docker push ${IMAGE}:${tag}
done
docker logout
