#!/bin/sh

if [ -z ${CIRCLECI} ]; then
  echo This only runs on circleci. >&2
  exit 1
fi

. test/vars.bash

if [ ${CIRCLE_BRANCH} == "master" ]; then
# TAG="$(date +%Y%m%dT%H%M)-git-${GIT_HASH:0:7}"
  TAG="$(date +%Y%m%dT%H%M)-git-${CIRCLE_SHA1:0:7}"
  tags="${TAG} latest"
else
  TAG="${CIRCLE_PR_USERNAME}_pull_${CIRCLE_PR_NUMBER}"
  tags="${TAG}"
fi

docker login -e ${mail} -u ${user} -p ${pass} 
for tag in ${tags}; do
  docker tag -f ${IMAGE} ${IMAGE}:${tag}
  docker push ${IMAGE}:${tag}
done
docker logout
